#include "PWM.h"

// [TODO]
void PWM_Init1() {
	// Enable GPIO Port E Clock
	// [TODO]
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOEEN;
	
	// Enable TIM1 Clock
	// [TODO]
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
	// Configure PE8
	// [TODO]
	GPIOE->MODER &= ~(3UL<<16);
	GPIOE->MODER |= 1UL<<17;
	
	GPIOE->OSPEEDR &= ~(3UL<<16);
	GPIOE->OSPEEDR |= 3UL<<16;
	
	GPIOE->PUPDR &= ~(3UL<<16);
	
	GPIOE->AFR[1] |= ~(15UL);
	GPIOE->AFR[1] |= 1;
	// Configure PWM Output for TIM1 CH 1N
	// [TODO]
	TIM1->CR1 &= 0 << 4;
	TIM1->ARR = 999UL;
	TIM1->PSC = 19UL;
	
	TIM1->CCMR1 &= 0UL<<24;
	TIM1->CCMR1 &= 0UL<<16;
	TIM1->CCMR1 &= ~(7UL<<12);
	TIM1->CCMR1 &= ~(7UL<<4);
	TIM1->CCMR1 |= 6UL<<4;
	TIM1->CCMR1 |= 1UL<<3;
	
	TIM1->CCER &= 0 << 3;
	TIM1->CCER |= 1 << 2;
	TIM1->BDTR |= 1UL<<15;
	TIM1->CCR1 = 500UL;
	TIM1->CR1 |= 1;
	
}

void PWM_Init2() {

	// Enable GPIO Port A Clock
	// [TODO]
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
	
	// Enable TIM8 Clock
	// [TODO]
	RCC->APB2ENR |= RCC_APB2ENR_TIM8EN;
	// Configure PA5
	// [TODO]
	GPIOA -> MODER &= ~GPIO_MODER_MODE5_0;
	GPIOA -> MODER |= GPIO_MODER_MODE5_1;
	
	GPIOA->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR5;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR5;
	
	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPD5;
	
	GPIOA -> AFR[0] &= ~GPIO_AFRL_AFRL5;
	GPIOA -> AFR[0] |= GPIO_AFRL_AFSEL5_0;
	GPIOA -> AFR[0] |= GPIO_AFRL_AFSEL5_1;
	// Configure PWM Output for TIM1 CH 1N
	// [TODO]
	TIM8->CR1 &= ~TIM_CR1_CEN;
	TIM8->CR1 &= ~TIM_CR1_DIR;
	TIM8->ARR = 999UL;
	TIM8->PSC = 19UL;
	
	TIM8->CCMR1 &= ~TIM_CCMR1_OC2M;
	TIM8->CCMR1 &= ~TIM_CCMR1_OC1M;
	TIM8->CCMR1 |= (TIM_CCMR1_OC1M_2|TIM_CCMR1_OC1M_1);
	TIM8->CCMR1 |= TIM_CCMR1_OC1PE;
	
	TIM8->CCER &= ~TIM_CCER_CC1NP;
	TIM8->CCER |= TIM_CCER_CC1NE;
	TIM8->BDTR |= TIM_BDTR_MOE;
	TIM8->CCR1 = 500UL;
	TIM8->CR1 |= TIM_CR1_CEN;
}

void PWM_Init3() {
	// Enable GPIO Port A Clock
	// [TODO]
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
	
	// Enable TIM2 Clock
	// [TODO]
	RCC->APB1ENR1 |= RCC_APB1ENR1_TIM2EN;
	// Configure PA0
	// [TODO]
	GPIOA -> MODER &= ~GPIO_MODER_MODE0_0;
	GPIOA -> MODER |= GPIO_MODER_MODE0_1;
	
	GPIOA->OSPEEDR &= ~GPIO_OSPEEDER_OSPEEDR0;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0;
	
	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPD0;
	
	GPIOA -> AFR[0] &= ~GPIO_AFRL_AFRL0;
	GPIOA -> AFR[0] |= GPIO_AFRL_AFSEL0_0;
	// Configure PWM Output for TIM2 CH 1
	// [TODO]
	TIM2->CR1 &= ~TIM_CR1_CEN;
	TIM2->CR1 &= ~TIM_CR1_DIR;
	TIM2->ARR = 999UL;
	TIM2->PSC = 19UL;
	
	TIM2->CCMR1 &= ~TIM_CCMR1_OC2M;
	TIM2->CCMR1 &= ~TIM_CCMR1_OC1M;
	TIM2->CCMR1 |= (TIM_CCMR1_OC1M_2|TIM_CCMR1_OC1M_1);
	TIM2->CCMR1 |= TIM_CCMR1_OC1PE;
	
	TIM2->CCER &= ~TIM_CCER_CC1P;
	TIM2->CCER |= TIM_CCER_CC1E;
	TIM2->BDTR |= TIM_BDTR_MOE;
	TIM2->CCR1 = 500UL;
	TIM2->CR1 |= TIM_CR1_CEN;
	
}

void writeValue(double value[3]) {
	TIM2->CCR1 = (value[0]/3) * TIM2->ARR;
	TIM1->CCR1 = (value[1]/3) * TIM1->ARR;
	TIM8->CCR1 = (value[2]/3) * TIM8->ARR;
}